/* Smoke test for the drop-in version.dll patcher (run under Wine/Proton).
 * Plants a fake, correctly-shaped zf.publicKey in writable memory, loads the
 * proxy, and checks (a) the string is rewritten to the server key and
 * (b) version.dll forwarding still answers. */
#include <windows.h>
#include <stdio.h>
#include <string.h>
#include <wchar.h>

#include "pubkey_blob.h"   /* generated by build.sh: the server key */

typedef DWORD (WINAPI *pfn_size)(LPCSTR, LPDWORD);

static wchar_t g_buf[2048];
static char g_abuf[1024];

int main(void) {
    wchar_t fake[1024];
    char afake[1024];
    int p = 0, q = 0, i;
    p += swprintf(fake + p, 100, L"<RSAKeyValue><Modulus>");
    for (i = 0; i < 344; i++) fake[p++] = L'A';
    p += swprintf(fake + p, 100, L"</Modulus><Exponent>AQAB</Exponent></RSAKeyValue>");
    fake[p] = 0;
    wcscpy(g_buf, fake);
    /* the game's real target is the ASCII metadata literal */
    q += sprintf(afake + q, "<RSAKeyValue><Modulus>");
    for (i = 0; i < 344; i++) afake[q++] = 'B';
    q += sprintf(afake + q, "</Modulus><Exponent>AQAB</Exponent></RSAKeyValue>");
    afake[q] = 0;
    strcpy(g_abuf, afake);

    HMODULE h = LoadLibraryA("version.dll");
    if (!h) { printf("FAIL LoadLibrary version.dll err=%lu\n", GetLastError()); return 2; }
    printf("loaded version.dll at %p\n", (void *)h);

    for (i = 0; i < 100; i++) {
        wchar_t* m = wcsstr(g_buf, L"<Modulus>");
        char* am = strstr(g_abuf, "<Modulus>");
        if (m && wcsncmp(m + 9, EZ2_PUB_MODULUS, 344) == 0 &&
            am && strncmp(am + 9, EZ2_PUB_MODULUS_A, 344) == 0) break;
        Sleep(100);
    }
    {
        wchar_t* m = wcsstr(g_buf, L"<Modulus>");
        char* am = strstr(g_abuf, "<Modulus>");
        if (!m || wcsncmp(m + 9, EZ2_PUB_MODULUS, 344) != 0) {
            printf("FAIL utf-16 publicKey not rewritten\n");
            return 1;
        }
        if (!am || strncmp(am + 9, EZ2_PUB_MODULUS_A, 344) != 0) {
            printf("FAIL ascii metadata literal not rewritten\n");
            return 1;
        }
    }
    printf("OK   utf-16 + ascii publicKey rewritten in place\n");

    pfn_size f = (pfn_size)GetProcAddress(h, "GetFileVersionInfoSizeA");
    printf("forward GetFileVersionInfoSizeA @ %p\n", (void *)f);
    if (f) {
        DWORD dummy = 0;
        DWORD r = f("kernel32.dll", &dummy);
        printf("forward call returned %lu (0 is a failure)\n", r);
        if (r == 0) return 3;
    } else {
        return 4;
    }
    printf("PASS\n");
    return 0;
}
