#!/usr/bin/env bash
# Build the drop-in version.dll patcher for EZ2ON REBOOT:R.
#   sudo pacman -S --needed mingw-w64-gcc
#   bash client/patcher/build.sh
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
PUB="$ROOT/server/data/server_rsa_public.xml"
CC="${CC:-x86_64-w64-mingw32-gcc}"

command -v "$CC" >/dev/null || {
  echo "missing $CC — install mingw-w64-gcc (Arch: sudo pacman -S mingw-w64-gcc)" >&2
  exit 1
}
[ -f "$PUB" ] || { echo "no $PUB — run: python server/_rsa.py init" >&2; exit 1; }

python3 - "$PUB" "$HERE/pubkey_blob.h" <<'PY'
import sys, re
xml = open(sys.argv[1], encoding='utf-8').read()
mod = re.search(r'<Modulus>(.*?)</Modulus>', xml, re.S).group(1).strip()
exp = re.search(r'<Exponent>(.*?)</Exponent>', xml, re.S).group(1).strip()
def cw(s):
    return ''.join(ch if ch.isalnum() or ch in '+/=' else '?' for ch in s)
with open(sys.argv[2], 'w') as f:
    f.write('/* generated by build.sh from server/data/server_rsa_public.xml */\n')
    f.write(f'static const WCHAR EZ2_PUB_MODULUS[] = L"{cw(mod)}";\n')
    f.write(f'static const WCHAR EZ2_PUB_EXPONENT[] = L"{cw(exp)}";\n')
    f.write(f'static const char  EZ2_PUB_MODULUS_A[] = "{cw(mod)}";\n')
    f.write(f'static const char  EZ2_PUB_EXPONENT_A[] = "{cw(exp)}";\n')
print(f'embedded modulus {len(mod)} chars, exponent {exp}')
PY

"$CC" -O2 -shared -static-libgcc -o "$HERE/version.dll" \
    "$HERE/ez2on_version_proxy.c" -lkernel32 -luser32
echo "built $HERE/version.dll"
