/* generated by build.sh from server/data/server_rsa_public.xml */
static const WCHAR EZ2_PUB_MODULUS[] = L"0fnCJfO39TB3e78Vg0yRfmKESmHA3joOUkkEWCH0XLDTYhvP5RH9e/y1vIDH3qSVCii8EjbEAIDtLvU8VAucMDjKbuVqmmv/9US/qpbYJuw+Gx8XO0eMup3ScOoF/L96iB9iOi+6y+uwaPmG9ZSOrBiTWjuvG3+zovjG9nqWmcxx7UbYCOLalSHculI6W0YVuiJuTc3JyzGaC5hVI2ymT4XR2mFMWUg/NMBw0SrD7STeuP+Dv/q3HgDLvNhdJXsFDmiTpaquZqiZEcXSQJhotoQANfc9ooAceliCe5/pOX9kwmpg5wH6AdMubJu0W2slx9bFyc9z32OBPsPFy/xL+Q==";
static const WCHAR EZ2_PUB_EXPONENT[] = L"AQAB";
static const char  EZ2_PUB_MODULUS_A[] = "0fnCJfO39TB3e78Vg0yRfmKESmHA3joOUkkEWCH0XLDTYhvP5RH9e/y1vIDH3qSVCii8EjbEAIDtLvU8VAucMDjKbuVqmmv/9US/qpbYJuw+Gx8XO0eMup3ScOoF/L96iB9iOi+6y+uwaPmG9ZSOrBiTWjuvG3+zovjG9nqWmcxx7UbYCOLalSHculI6W0YVuiJuTc3JyzGaC5hVI2ymT4XR2mFMWUg/NMBw0SrD7STeuP+Dv/q3HgDLvNhdJXsFDmiTpaquZqiZEcXSQJhotoQANfc9ooAceliCe5/pOX9kwmpg5wH6AdMubJu0W2slx9bFyc9z32OBPsPFy/xL+Q==";
static const char  EZ2_PUB_EXPONENT_A[] = "AQAB";
